"""Graph topology metrics for multi-agent simulation networks.

Three groups of metrics: basic structure (density, degrees, reciprocity), the
in-degree distribution (power-law exponent) and community structure (clustering,
modularity).
"""

import logging
from typing import Any, Dict

import networkx as nx
import numpy as np
import powerlaw

logger = logging.getLogger(__name__)

# Metrics summarised by the pipelines and used by default in tests and figures.
KEY_METRICS = [
    "alpha_in_degree",
    "modularity",
    "average_clustering",
    "density",
]


class GraphMetrics:
    """Computes topological metrics on any directed graph.

    The report generated by generate_full_report() is a flat, serializable
    dictionary, so a list of reports turns straight into a DataFrame.

    Args:
        G: Directed graph to analyse.

    Raises:
        TypeError: If G is not an nx.DiGraph.
        ValueError: If graph has no nodes.
    """

    def __init__(self, G: nx.DiGraph) -> None:
        if not isinstance(G, nx.DiGraph):
            raise TypeError(f"Expected nx.DiGraph, got {type(G).__name__}.")
        if G.number_of_nodes() == 0:
            raise ValueError("Graph contains no nodes.")

        self.G = G
        # Undirected view for clustering and modularity calculations
        self.G_undirected: nx.Graph = G.to_undirected()

    def compute_basic_stats(self) -> Dict[str, Any]:
        """Compute fundamental structural statistics of the network.

        Reciprocity is the fraction of edges that are mutual. The in-degree
        standard deviation is a quick check on how unevenly followers are spread:
        real follower networks are strongly skewed, so a very small value is suspicious.

        Returns:
            Dictionary with keys: num_nodes, num_edges, density, avg_in_degree,
            std_in_degree, avg_out_degree, std_out_degree, reciprocity.
        """
        in_degrees = np.array([d for _, d in self.G.in_degree()])
        out_degrees = np.array([d for _, d in self.G.out_degree()])

        return {
            "num_nodes": self.G.number_of_nodes(),
            "num_edges": self.G.number_of_edges(),
            "density": float(nx.density(self.G)),
            "avg_in_degree": float(np.mean(in_degrees)),
            "std_in_degree": float(np.std(in_degrees)),
            "avg_out_degree": float(np.mean(out_degrees)),
            "std_out_degree": float(np.std(out_degrees)),
            "reciprocity": float(nx.reciprocity(self.G)),
        }

    def compute_powerlaw_alpha(self) -> Dict[str, Any]:
        """Estimate power-law exponent α from in-degree distribution.

        Empirical scale-free networks usually have 2 < α < 3; a lower value means
        followers are concentrated on even fewer hubs. ks_distance is the
        Kolmogorov-Smirnov distance between the data and the fitted tail.

        Returns:
            Dictionary with keys: alpha_in_degree, xmin, ks_distance,
            is_scale_free, powerlaw_error.
        """
        in_degrees = [d for _, d in self.G.in_degree() if d > 0]

        if len(in_degrees) < 10:
            logger.warning(
                "Power-law fit skipped: only %d non-zero in-degrees.", len(in_degrees)
            )
            return {
                "alpha_in_degree": None,
                "xmin": None,
                "ks_distance": None,
                "is_scale_free": None,
                "powerlaw_error": f"Insufficient data ({len(in_degrees)} in-degree > 0).",
            }

        try:
            # discrete=True assumes in-degrees are integers
            fit = powerlaw.Fit(in_degrees, discrete=True, verbose=False)
            alpha = float(fit.alpha)
            return {
                "alpha_in_degree": round(alpha, 4),
                "xmin": float(fit.xmin),
                "ks_distance": round(float(fit.D), 4),
                "is_scale_free": 2.0 < alpha < 3.0,
                "powerlaw_error": None,
            }
        except Exception as exc:
            logger.error("Power-law fitting failed: %s", exc)
            return {
                "alpha_in_degree": None,
                "xmin": None,
                "ks_distance": None,
                "is_scale_free": None,
                "powerlaw_error": str(exc),
            }

    def compute_clustering_and_modularity(self) -> Dict[str, Any]:
        """Compute average clustering coefficient and network modularity.

        Modularity Q lies in [-1, 1]; above roughly 0.3 is usually read as clear
        community structure. Both are computed on the undirected version of the graph.

        Returns:
            Dictionary with keys: average_clustering, modularity, num_communities.
        """
        avg_clustering = float(nx.average_clustering(self.G_undirected))
        # greedy_modularity_communities is deterministic (no seed needed)
        communities = nx.community.greedy_modularity_communities(self.G_undirected)
        modularity = float(nx.community.modularity(self.G_undirected, communities))

        return {
            "average_clustering": round(avg_clustering, 4),
            "modularity": round(modularity, 4),
            "num_communities": len(communities),
        }

    def generate_full_report(self) -> Dict[str, Any]:
        """Generate complete topological report ready for multi-run aggregation.

        Returns:
            Flat dictionary containing all metrics from basic_stats,
            powerlaw_alpha, and clustering_and_modularity.
        """
        report: Dict[str, Any] = {}
        report.update(self.compute_basic_stats())
        report.update(self.compute_powerlaw_alpha())
        report.update(self.compute_clustering_and_modularity())
        return report
